### PR TITLE
Set encoding and source/target Java versions

### PR DESCRIPTION
**Pull request by ghost**
- Setting the encoding fixes a warning about possibly platform-dependent behavior
- Setting the source/target Java versions allows it to compile (at least for the JDK I'm using)

### CODE REVIEW

**Comment by Hrothen** [comment]
1.5 is the default maven source and target, if you're needing to set it to that explicitly then you have some other setting overriding it on your system. Setting the version to the default explicitly will break building for people who have configured their maven to build with a modern version of Java system-wide.

**Comment by ghost** [comment]
I agree that's the default. I can't explain what I'm seeing. All I know is that if I use Maven 3.0.5 and Oracle's JDK (1.8.0_60) then I cannot compile this repository:

```
mvn package
...some output...
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.0.2:compile (default-compile) on project relevancy-profiler: Compilation failure: Compilation failure:
[ERROR] path/to/wex-engine-relevancy-profiler/src/main/java/com/ibm/wex/relevancyprofiler/filters/QueriesWithNoResultsFilter.java:[15,12] error: generics are not supported in -source 1.3
[ERROR] 
[ERROR] (use -source 5 or higher to enable generics)
```

But if I set source and target, it works.

I see no harm in having the pom.xml specify the source or the target: The pom should tell the JDK whether it requires newer Java features/constructs/whatever. The compilation shouldn't depend on the user's system-wide defaults. The target is less important in my opinion, but having 1.5 being the target version ensures maximum backwards compatibility (although it's ancient at this point).

**Comment by colindean** [comment]
Maven 3.0.5 is pretty ancient, no? Maven 3.2.2 seems to be our standard for new projects. 

It's pretty safe to set both target and source to `1.7`. All _supported_ versions of WEX ship 1.7+.

**Comment by michaelkeeling** [comment]
This change works for me.  But so did the old pom.... I'm actually quite indifferent about the build system as long as it works for people other than me (which it doesn't seem to currently).  I agree with Colin's assertion about Java 1.7.  I see no reason to assume a source/target < 1.7.

I'm going to go ahead and merge this and we can always change settings or build systems later if someone is passionate about it.

**Pull request merged**
